### ISSUE TITLE
NPE in LaunchActivity#wireButtons();

### ISSUE THREAD

**Issue by deanrobertcook** [deanrobertcook/Android-BudgetTracker#33]
```
Process: org.theronin.expensetracker, PID: 31578
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{org.theronin.expensetracker/org.theronin.expensetracker.pages.launch.LaunchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.theronin.expensetracker.pages.launch.LaunchFragment.getPositiveButtonText()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.theronin.expensetracker.pages.launch.LaunchFragment.getPositiveButtonText()' on a null object reference
                                                                                 at org.theronin.expensetracker.pages.launch.LaunchActivity.wireUpButtons(LaunchActivity.java:90)
                                                                                 at org.theronin.expensetracker.pages.launch.LaunchActivity.onAttachFragment(LaunchActivity.java:86)
                                                                                 at android.app.Activity$HostCallbacks.onAttachFragment(Activity.java:6662)
                                                                                 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
                                                                                 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                                                 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
                                                                                 at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1948)
                                                                                 at android.app.FragmentController.dispatchCreate(FragmentController.java:141)
                                                                                 at android.app.Activity.onCreate(Activity.java:921)
                                                                                 at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39)
                                                                                 at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:278)
                                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:61)
                                                                                 at org.theronin.expensetracker.pages.launch.LaunchActivity.onCreate(LaunchActivity.java:27)
                                                                                 at android.app.Activity.performCreate(Activity.java:6251)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by deanrobertcook** [comment]
Haven't seen in a while
