### ISSUE TITLE
Object Graph not created after app has been killed

### ISSUE THREAD

**Issue by deanrobertcook** [deanrobertcook/Android-BudgetTracker#34]
```
FATAL EXCEPTION: main
                                                                           Process: org.theronin.expensetracker, PID: 6391
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{org.theronin.expensetracker/org.theronin.expensetracker.pages.main.MainActivity}: java.lang.IllegalStateException: The Object graph has not been established yet. This means the database is also not ready
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:211)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                            Caused by: java.lang.IllegalStateException: The Object graph has not been established yet. This means the database is also not ready
                                                                               at org.theronin.expensetracker.CustomApplication.inject(CustomApplication.java:55)
                                                                               at org.theronin.expensetracker.dagger.InjectedActivity.inject(InjectedActivity.java:16)
                                                                               at org.theronin.expensetracker.dagger.InjectedFragment.inject(InjectedFragment.java:16)
                                                                               at org.theronin.expensetracker.dagger.InjectedFragment.onAttach(InjectedFragment.java:11)
                                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:853)
                                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                               at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                                               at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1864)
                                                                               at android.app.Activity.onCreate(Activity.java:936)
                                                                               at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39)
                                                                               at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:278)
                                                                               at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:61)
                                                                               at org.theronin.expensetracker.dagger.InjectedActivity.onCreate(InjectedActivity.java:10)
                                                                               at org.theronin.expensetracker.pages.main.MainActivity.onCreate(MainActivity.java:68)
                                                                               at android.app.Activity.performCreate(Activity.java:5990)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:156) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:211) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5373) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
```

**Comment by deanrobertcook** [comment]
Not using dagger anymore - got a similar issue with my own solution though, so it might be a deeper issue...
