### ISSUE TITLE
Seems a Fragment is not attached properly

### ISSUE THREAD

**Issue by deanrobertcook** [deanrobertcook/Android-BudgetTracker#35]
```
FATAL EXCEPTION: main
                                                   Process: org.theronin.expensetracker, PID: 22353
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                       at android.widget.Toast.<init>(Toast.java:102)
                                                       at android.widget.Toast.makeText(Toast.java:259)
                                                       at org.theronin.expensetracker.pages.launch.SignInFragment$1.done(SignInFragment.java:58)
                                                       at org.theronin.expensetracker.pages.launch.SignInFragment$1.done(SignInFragment.java:51)
                                                       at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:115)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by deanrobertcook** [comment]
Haven't seen this in a while
